base.folder.textures=C:\\Users\\jmart\\Projects\\MGR3DEngine\\src\\main\\resources\\Textures
base.folder.shaders=C:\\Users\\jmart\\Projects\\MGR3DEngine\\src\\main\\resources\\Shaders
base.folder.models=C:\\Users\\jmart\\Projects\\MGR3DEngine\\Models
