item.model_file=\\monster\\monster.md5mesh
item.model_textures=\\monster\\textures
item.scale=0.4f
item.position=151.0f,0.0f,50.0f
item.rotation=0.0f,90.0f,0.0f
# Check com.mgr.engine.shaders.ShaderType.java to see all options
item.shader_type=AnimatedItemShader
